AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Nova Data Harvest - state machine + lambdas

Parameters:
  ProjectName:
    Type: String
    Default: nova-data-harvest
  LogLevel:
    Type: String
    Default: INFO
  DataBucketName:
    Type: String
    Default: nova-data-bucket-finzell
    Description: S3 bucket holding inputs/outputs

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    # Runtime: python3.11
    Architectures: 
      - arm64
    # PackageType: Image
    Environment:
      Variables:
        APP_NAME: nova-data-harvest
        S3_BUCKET: nova-data-bucket-finzell
        ADS_SNAPSHOT_PREFIX: harvest/snapshots/ads/
        MANIFEST_PREFIX: harvest/manifests/
        RECENCY_BOOST_DAYS: "90"

Resources:
  InitContextFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nova-data-harvest-init-context
      PackageType: Image         # or Zip if you prefer
      ImageConfig:
        Command: ["app.handler"]
      Description: Initializes run context for nova-data-harvest
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DataBucketName
        - S3WritePolicy:
            BucketName: !Ref DataBucketName
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile
  
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: nova-data-harvest
      DefinitionUri: statemachine/nova-data-harvest.asl.json
      DefinitionSubstitutions:
        InitContextArn: !GetAtt InitContextFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref InitContextFunction


Outputs:
  StateMachineArn:
    Value: !Ref StateMachine
  InitContextFunctionArn:
    Value: !GetAtt InitContextFunction.Arn
