#Dynamo DB Template
Resources:
  HarvestQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nova-ingest-harvest-queue
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1_pk
          AttributeType: S
        - AttributeName: gsi1_sk
          AttributeType: S
        - AttributeName: gsi2_pk
          AttributeType: S
        - AttributeName: gsi2_sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1_pk
              KeyType: HASH
            - AttributeName: gsi1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [pk, sk, author_count, nova_id, bibcode, open_access_url, oa_reason, data]
        - IndexName: GSI2
          KeySchema:
            - AttributeName: gsi2_pk
              KeyType: HASH
            - AttributeName: gsi2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: [pk, sk, status, priority, updated_at]
